#!/usr/bin/env python3
"""Generate RGB metal IOR presets from five local refractiveindex.info files.

Output: src/generated/metal_presets.h (C++17, CPU-side lookup table).

Uses Python 3 standard library. Reader supports the single
`tabulated nk` literal data block in these five files, not arbitrary YAML.
Input wavelengths are micrometers; n (eta) and k are dimensionless.
Sampling at 650/550/450 nm is an approximate RGB representation.
"""

import argparse
import hashlib
import math
import re
from bisect import bisect_left
from pathlib import Path

# Array order is the metallicPresetID order used in path tracer.
PRESETS = (
    ("Gold", "Au", "Johnson"),
    ("Silver", "Ag", "Johnson"),
    ("Copper", "Cu", "Johnson"),
    ("Aluminum", "Al", "Rakic"),
    ("Chrome (chromium)", "Cr", "Johnson"),
)
CHANNELS = (("R", 0.650), ("G", 0.550), ("B", 0.450))
SOURCE_ROOT = (
    "https://raw.githubusercontent.com/polyanskiy/"
    "refractiveindex.info-database/master/database/data/main"
)


def read_samples(path):
    """Return original bytes and sorted (wavelength_um, eta, k) rows."""
    raw = path.read_bytes()
    rows = []
    saw_type = False
    block_indent = None

    for line_number, line in enumerate(raw.decode("utf-8-sig").splitlines(), 1):
        content = line.split("#", 1)[0].strip()
        if not content:
            continue
        indent = len(line) - len(line.lstrip())

        if block_indent is None:
            if re.fullmatch(r"-\s*type:\s*tabulated nk", content):
                saw_type = True
            elif saw_type and re.fullmatch(r"data:\s*\|[+-]?", content):
                block_indent = indent
            continue

        if indent <= block_indent:
            break

        try:
            wavelength, eta, k = map(float, content.split())
        except ValueError as exc:
            raise ValueError(
                f"{path}:{line_number}: expected wavelength, eta, k"
            ) from exc

        if not all(math.isfinite(v) for v in (wavelength, eta, k)):
            raise ValueError(f"{path}:{line_number}: non-finite coefficient")
        if wavelength <= 0 or eta < 0 or k < 0:
            raise ValueError(f"{path}:{line_number}: invalid optical data")
        if rows and wavelength <= rows[-1][0]:
            raise ValueError(f"{path}:{line_number}: wavelengths must increase")
        rows.append((wavelength, eta, k))

    if len(rows) < 2:
        raise ValueError(f"{path}: expected a tabulated nk block with >= 2 rows")
    return raw, rows


def interpolate(rows, target):
    """Return eta, k, lower row, upper row, and interpolation weight."""
    if not rows[0][0] <= target <= rows[-1][0]:
        raise ValueError(f"{target} um is outside the dataset's wavelength range")

    index = bisect_left([row[0] for row in rows], target)
    upper = rows[index]
    if upper[0] == target:
        return upper[1], upper[2], upper, upper, 0.0

    lower = rows[index - 1]
    t = (target - lower[0]) / (upper[0] - lower[0])
    eta = lower[1] + t * (upper[1] - lower[1])
    k = lower[2] + t * (upper[2] - lower[2])
    return eta, k, lower, upper, t


def cpp_vec3(values):
    return "glm::vec3(" + ", ".join(f"{v:.9f}f" for v in values) + ")"


def generate(data_dir):
    """Compute every preset before returning a complete header."""
    lines = [
        "#pragma once",
        "#include <glm/glm.hpp>",
        "",
        "// Generated by tools/generate_metal_presets.py; regenerate to edit.",
        "// Sources: refractiveindex.info database (CC0 1.0).",
        "// License: https://creativecommons.org/publicdomain/zero/1.0/",
        "// Source YAML files retain the original publication references.",
        "// Piecewise linear interpolation at RGB = 650, 550, 450 nm.",
        "// Approximate RGB coefficients, not  full spectral-to-RGB conversion.",
        "// eta and k are dimensionless; do not clamp to [0, 1].",
        "// CPU lookup: copy  selected coefficients into  GPU Material.",
        "",
        "struct MetalIORPreset {",
        "    glm::vec3 eta;",
        "    glm::vec3 k;",
        "};",
        "",
        "inline const MetalIORPreset metalIORPresets[] = {",
    ]

    for preset_id, (name, symbol, study) in enumerate(PRESETS):
        filename = f"{symbol}-{study}.yml"
        raw, rows = read_samples(data_dir / filename)
        eta_rgb, k_rgb = [], []
        print(f"\n{preset_id}: {name} ({filename}, {len(rows)} samples)")

        for channel, target in CHANNELS:
            eta, k, lower, upper, t = interpolate(rows, target)
            eta_rgb.append(eta)
            k_rgb.append(k)
            print(f"  {channel}: target={target:.3f} um")
            print(f"    lower (wavelength_um, eta, k): {lower}")
            print(f"    upper (wavelength_um, eta, k): {upper}")
            print(f"    t={t:.12g}; eta={eta:.12g}; k={k:.12g}")

        lines.extend(
            [
                f"    // {preset_id}: {name}",
                f"    // Source file: {filename}",
                f"    // {SOURCE_ROOT}/{symbol}/nk/{study}.yml",
                f"    // Source SHA-256: {hashlib.sha256(raw).hexdigest()}",
                "    {",
                f"        {cpp_vec3(eta_rgb)},",
                f"        {cpp_vec3(k_rgb)}",
                "    },",
            ]
        )

    lines.extend(["};", ""])
    return "\n".join(lines)


def main():
    project_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=project_root / "data" / "ior",
        help="Input directory (default: project's data/ior, relative to script)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=project_root / "src" / "generated" / "metal_presets.h",
        help="Output header (default: project's src/generated/metal_presets.h)",
    )
    args = parser.parse_args()

    try:
        header = generate(args.data_dir)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with args.output.open("w", encoding="utf-8", newline="\n") as output:
            output.write(header)
    except (OSError, UnicodeError, ValueError) as exc:
        parser.exit(1, f"\nError: {exc}\n")

    print(f"\nWrote {args.output.resolve()}")


if __name__ == "__main__":
    main()
